language: elixir
elixir:
- 1.2
otp_release:
- 18.2
sudo: false
addons:
  postgresql: '9.4'
before_script:
- psql -c 'create database peepchat_test;' -U postgres
deploy:
  provider: heroku
  api_key:
    secure: iQz7TnqIDoYFrSATrUno5Yao/spqzxBBDXD0l+a3p75u11kneSQWyQ4HjxdGmkR8WMPf14zQRMkpQj9vdhe9spSFHq02EaPZjeGUiQOhiy98Gga98wlpXTbPpmi+MaRYJpftQNRtdFtxxiP0hqlaoEXAplwRdO0tkaeLjplb1TGBOvLzWWMB88JoxRyVBS2Gg/VmeXo7QSRs12zl7qdxcXbX8hpDI9B5PuJiFZLIIYssowvvYI/sgIuRu0HeyGubc1fzZP1PQkd3h0e8siYw81xVOJO5LyD9oM+zwos6lTrDHFC+Lp4hHvyYR55MJAv+b5rciAKH7qWHcx+1QnqeEatOW+liuUbYGZVjUgw2pBUN7fWQB+masCOuVjxuZEwwe8ATeuiarOIcNIsKy4kPeUuoOJN3j4McvPgpYeEfr7NTiMh1fPJjcpLp5tYuDQc4hmh3inx/BQu7mHeWQP+0wNq67h/GkV7sDP+QP6lsXF4ojzdJDI5Z1GTg1WrIlkw++MIEyjnwUmmKZm5yGaAsYyJA5tRun+0fi94+XAMs9xbX/cuEda3QZdNZ/TLqqY83+E8ercjTGFIlfjHpFTnjDGT7ld/65FPOEF4D/KoP2ZO17i5h6LJiDUHTk5cvCfUnK1ykTxVgts3wfFhv7mDwxhpi57lEOi57gWGEjaeMuJI=
  app: evening-anchorage-10217
  on:
    repo: FruitPunchSamuraiS/peepchat-api
